// ══ AVATAR REGISTRY — illustrated preset set (Pulse style) ════════════════
// The single source of truth for selectable account avatars. Each entry maps a
// stable `id` (persisted in settingsStore.avatarId + synced per-UID) to a
// renderable asset. Founder pick 2026-06-12 "Preset-uri ilustrate" — an
// illustrated preset set in the Pulse line-art style, no real faces, athletic +
// gender-neutral, friendly for both Gigel and Maria 65.
//
// SWAPPABLE ASSET LAYER (design directive): the renderer (UserAvatar) branches
// on `kind`. Today every entry is `kind: 'svg'` — an inline Pulse line-art glyph
// (zero asset bytes, theme-token colored, scales crisp at any px). A future
// founder-generated AI image set (square PNG/webp, emerald/teal accents) drops
// in with ZERO refactor: add `{ id, kind: 'image', src: '/avatars/<id>.webp' }`
// entries (or flip an existing id's kind+src). UserAvatar already renders the
// <img> branch. No consumer, store, or persistence change is needed — the id
// contract is stable, only the asset behind it changes.
//
// Colors: LIVE Pulse tokens only (--volt emerald / --aqua teal / --ember amber /
// --violet) — never raw hex, so avatars track theme + the accent picker palette.
// The glyph fill colors below are token var() strings resolved at render.
//
// A11y: the human-readable name lives in i18n under `cont.avatar.presets.<id>`
// (UserAvatar / AvatarPicker pass it as aria-label); this module stays
// string-free for locale independence.

import type { JSX } from 'react';
import {
  glyphHeartbeat,
  glyphTarget,
  glyphBolt,
  glyphMountain,
  glyphLeaf,
  glyphOrbit,
  glyphPrism,
  glyphSpark,
} from './glyphs';

/** A Pulse accent token used as the glyph stroke/fill. */
export type AvatarAccent =
  | 'var(--volt)'
  | 'var(--aqua)'
  | 'var(--ember)'
  | 'var(--violet)';

/**
 * A preset avatar. `kind` selects the render branch in UserAvatar:
 *   - 'svg'   → `glyph` draws an inline Pulse line-art path (current set).
 *   - 'image' → `src` points at a square raster (future founder AI set). The
 *               glyph/accent fields are ignored for image entries.
 * The id is the persisted contract — keep ids stable across asset swaps.
 */
export interface AvatarPreset {
  /** Stable persisted id (settingsStore.avatarId). Never reuse/rename. */
  id: string;
  kind: 'svg' | 'image';
  /** SVG entries: the Pulse accent token the glyph is drawn in. */
  accent?: AvatarAccent;
  /** SVG entries: renders the inner glyph at the given accent (viewBox 0 0 48 48). */
  glyph?: (accent: AvatarAccent) => JSX.Element;
  /** Image entries (future AI set): absolute/public URL to a square asset. */
  src?: string;
}

// THE FOUNDER SET (2026-06-12) — 16 illustrated avatars generated by Daniel
// (round, transparent-bg, Andura "A" on the shirt; processed trim→square→256
// webp from salafull/public/avatars via sharp). They lead the grid as the
// canonical "Preset-uri ilustrate" pick. The 8 ABSTRACT svg marks stay after
// them (neutral/non-person options — the Maria-65 / "nu vreau o persoana"
// gap until the founder adds older-presenting illustrations). The 4 figure
// glyphs (athlete/figure/runner/flex) are RETIRED — the illustrated set
// replaces figure duty (removed pre-release, no saved picks could reference
// them; an unknown saved id degrades to initials by design anyway).
export const AVATAR_PRESETS: readonly AvatarPreset[] = [
  { id: 'ai-01', kind: 'image', src: '/avatars/ai-01.webp' },
  { id: 'ai-02', kind: 'image', src: '/avatars/ai-02.webp' },
  { id: 'ai-03', kind: 'image', src: '/avatars/ai-03.webp' },
  { id: 'ai-04', kind: 'image', src: '/avatars/ai-04.webp' },
  { id: 'ai-05', kind: 'image', src: '/avatars/ai-05.webp' },
  { id: 'ai-06', kind: 'image', src: '/avatars/ai-06.webp' },
  { id: 'ai-07', kind: 'image', src: '/avatars/ai-07.webp' },
  { id: 'ai-08', kind: 'image', src: '/avatars/ai-08.webp' },
  { id: 'ai-09', kind: 'image', src: '/avatars/ai-09.webp' },
  { id: 'ai-10', kind: 'image', src: '/avatars/ai-10.webp' },
  { id: 'ai-11', kind: 'image', src: '/avatars/ai-11.webp' },
  { id: 'ai-12', kind: 'image', src: '/avatars/ai-12.webp' },
  { id: 'ai-13', kind: 'image', src: '/avatars/ai-13.webp' },
  { id: 'ai-14', kind: 'image', src: '/avatars/ai-14.webp' },
  { id: 'ai-15', kind: 'image', src: '/avatars/ai-15.webp' },
  { id: 'ai-16', kind: 'image', src: '/avatars/ai-16.webp' },
  { id: 'heartbeat', kind: 'svg', accent: 'var(--volt)', glyph: glyphHeartbeat },
  { id: 'target', kind: 'svg', accent: 'var(--aqua)', glyph: glyphTarget },
  { id: 'bolt', kind: 'svg', accent: 'var(--ember)', glyph: glyphBolt },
  { id: 'mountain', kind: 'svg', accent: 'var(--violet)', glyph: glyphMountain },
  { id: 'leaf', kind: 'svg', accent: 'var(--volt)', glyph: glyphLeaf },
  { id: 'orbit', kind: 'svg', accent: 'var(--aqua)', glyph: glyphOrbit },
  { id: 'prism', kind: 'svg', accent: 'var(--ember)', glyph: glyphPrism },
  { id: 'spark', kind: 'svg', accent: 'var(--violet)', glyph: glyphSpark },
];

/** Map for O(1) id → preset resolution (UserAvatar render path). */
const PRESET_BY_ID: ReadonlyMap<string, AvatarPreset> = new Map(
  AVATAR_PRESETS.map((p) => [p.id, p]),
);

/** Resolve a preset by id. Returns null for an unknown/null id (→ initials
 *  fallback in UserAvatar). Pure — safe in render. */
export function getAvatarPreset(id: string | null | undefined): AvatarPreset | null {
  if (!id) return null;
  return PRESET_BY_ID.get(id) ?? null;
}

/** i18n key for a preset's human-readable name (aria-label / picker caption). */
export function avatarPresetLabelKey(id: string): string {
  return `cont.avatar.presets.${id}`;
}
