// ══ EXERCISE MEDIA — Visual guidance pipeline V1 (Daniel 2026-05-28 #11) ══
// Daniel smoke 2026-05-28: "vreau sa adaugam si poze sau gif-uri la fiecare
// exercitiu pentru visual guidance". Without a movement image/GIF, a beginner
// (Gigel/Maria 65) reads "Impins militar sezand" + "Cu gantere" and has to
// imagine the movement — friction + form-risk + adherence-killer.
//
// V1 SCOPE = pipeline foundation, NOT full 657-exercise sourcing:
//   1. Type-safe media metadata (URL + type + optional credit)
//   2. <ExerciseMedia> presentation component (wired by callers) — see
//      ../components/ExerciseMedia.tsx
//   3. Sample mapping for the top ~10 mockup-demo exercises so the UX is
//      live-visible immediately and Daniel can judge the format / placement.
//
// V2 (out of scope this commit) = source full library. Tradeoffs surfaced to
// Daniel:
//   - WGER (https://wger.de/api/v2/) — CC-BY-SA, free, ~400+ exercise
//     animations, REST API. Caveat: external dependency / hotlink hygiene.
//   - ExRx (https://exrx.net/) — proprietary, paywalled, highest production
//     quality. Not a free path.
//   - Custom commission — full creative control, expensive (~50-100 EUR per
//     movement at scale), slow.
//   - Lottie animation JSON — Linear/Vercel taste, requires custom asset
//     work but extremely lightweight + theme-tintable. V2 candidate.
//
// V1 recommendation: ship WGER URLs for the demo set (provenance verified
// below), placeholder for unknowns; v2 = source decision Daniel-gated.

import { toExerciseDisplay } from './exerciseDisplay';

export type ExerciseMediaType = 'image' | 'gif' | 'video' | 'lottie';

export interface ExerciseMediaInfo {
  /** Absolute or relative URL to the media asset (start of the movement). */
  url: string;
  /** Optional second frame (end of the movement) — shown side-by-side in the
   *  card variant so the user sees the full range. */
  url2?: string;
  /** Media kind — determines render: <img>, <video>, lottie player. */
  type: ExerciseMediaType;
  /** Provenance/credit (e.g. "WGER CC-BY-SA"). Visible only on the detail
   *  view (not the workout card) to keep the workflow uncluttered. */
  credit?: string;
  /** Optional alt text override; defaults to "Demonstratie {nameRo}". */
  alt?: string;
}

// V2 source (Wave 2, 2026-06-04) — interim demo images from free-exercise-db
// (PUBLIC DOMAIN / Unlicense, commercially safe). Small webp (~360px, ~9 KB avg)
// live in `public/exercise-media/<slug>.webp`, served lazily by URL and EXCLUDED
// from the PWA precache (vite.config workbox globIgnores `exercise-media/**`) so
// they NEVER bloat the bundle or the install — only fetched when an exercise card
// is opened, then runtime-cached. Daniel's own consistent photos overwrite
// per-slug later (same path) with zero code change.
//
// MANIFEST = the exact slugs that HAVE a file (so we return null — placeholder —
// for the rest, no 404 flash). Generated by scripts/_fetch_exercise_media.cjs
// (scripts/_media_slugs.json). Only the curated 1:1 matches are present, so a
// shown image is always the CORRECT movement (a near-miss stays a placeholder).
const EXERCISE_MEDIA_SLUGS: ReadonlySet<string> = new Set([
  'ab-wheel-rollout', 'assisted-dip-machine', 'band-assisted-pull-up', 'band-leg-curl',
  'band-pull-apart', 'barbell-back-squat-high-bar', 'barbell-curl-standing', 'barbell-row',
  'bayesian-curl', 'bb-shrug', 'belt-squat', 'bicycle-crunch',
  'bodyweight-squat', 'bulgarian-split-squat', 'cable-crossover-high-to-low', 'cable-crunch-kneeling',
  'cable-curl', 'cable-fly', 'cable-glute-kickback', 'cable-hammer-curl-rope',
  'cable-lateral-raise', 'cable-overhead-triceps-extension-rope', 'cable-pull-through', 'cable-rear-delt-fly',
  'cable-row', 'cable-single-arm-overhead-triceps-extension', 'cable-triceps-pushdown-rope', 'cable-triceps-pushdown-single-arm',
  'cable-triceps-pushdown-straight-bar', 'cable-triceps-pushdown-v-bar', 'cable-woodchop-high-to-low', 'captains-chair-leg-raise',
  'chest-supported-db-row', 'chest-supported-row', 'chin-up', 'close-grip-bench-press',
  'converging-chest-press', 'db-curl-standing', 'db-fly', 'db-hammer-curl-standing',
  'db-hip-thrust', 'db-lateral-raise', 'db-lunge', 'db-overhead-triceps-extension-two-hand',
  'db-rear-delt-fly', 'db-romanian-deadlift', 'db-row', 'db-shoulder-press',
  'db-shrug', 'db-single-leg-rdl', 'dead-bug', 'diamond-push-up',
  'dip', 'ez-bar-curl-standing', 'ez-bar-preacher-curl', 'face-pull',
  'farmer-s-walk-db', 'farmer-s-walk-trap-bar', 'flat-barbell-bench', 'flat-chest-press-machine',
  'flat-db-press', 'floor-press-barbell', 'front-squat', 'glute-bridge-bodyweight',
  'glute-drive-machine', 'glute-ham-raise', 'goblet-squat', 'hack-squat-machine',
  'hammer-strength-row', 'hanging-knee-raise', 'hanging-leg-raise', 'hip-thrust',
  'hyperextension-bodyweight', 'incline-barbell-bench', 'incline-chest-press-machine', 'incline-db-curl',
  'incline-db-press', 'incline-push-up', 'inverted-row-bar', 'knee-push-up',
  'landmine-t-bar-row', 'lat-pulldown', 'leaning-lateral-raise', 'leg-curl',
  'leg-extension', 'leg-extension-single-leg', 'leg-press', 'leg-press-calf-raise',
  'lying-triceps-extension-ez-bar', 'machine-lateral-raise', 'machine-pullover', 'machine-seated-curl',
  'machine-shoulder-press', 'neutral-grip-lat-pulldown', 'ohp', 'pallof-press-cable-standing',
  'pec-deck-cable-fly', 'pendlay-row', 'pendulum-squat', 'plank',
  'plate-loaded-hip-thrust-machine', 'pull-up', 'push-up', 'reverse-crunch',
  'reverse-curl-ez-bar', 'reverse-hyper', 'reverse-lunge', 'reverse-pec-deck',
  'romanian-deadlift', 'seated-calf-raise-machine', 'seated-db-press', 'seated-leg-curl',
  'side-plank', 'single-arm-cable-row', 'single-leg-calf-raise-bodyweight', 'single-leg-glute-bridge',
  'smith-close-grip-bench', 'smith-hip-thrust', 'smith-incline-bench', 'smith-machine-bench',
  'smith-machine-squat', 'smith-ohp', 'smith-standing-calf-raise', 'standing-calf-raise-machine',
  'standing-db-calf-raise', 'standing-leg-curl', 'straight-arm-lat-pulldown', 't-bar-row-machine',
  'trap-bar-deadlift', 'triceps-press-machine', 'v-bar-cable-row', 'v-bar-lat-pulldown',
  'walking-lunge', 'weighted-pull-up', 'wide-grip-lat-pulldown', 'wrist-roller',
  'y-raise',
]);

// Slug from an engine name — MUST match the filename slug the fetch script wrote
// (lowercase, non-alphanumerics → '-', trimmed). Keep in sync with
// scripts/_fetch_exercise_media.cjs `slugify`.
function toMediaSlug(engineName: string): string {
  return engineName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

/**
 * Look up media info for an engine exercise name. Returns the public-domain
 * interim image when one exists for this movement, else null (the
 * <ExerciseMedia> component then renders its muscle-group placeholder).
 */
export function getExerciseMedia(engineName: string): ExerciseMediaInfo | null {
  const slug = toMediaSlug(engineName);
  if (!EXERCISE_MEDIA_SLUGS.has(slug)) return null;
  return {
    url: `/exercise-media/${slug}.webp`,
    url2: `/exercise-media/${slug}-2.webp`,
    type: 'image',
    credit: 'Public domain',
  };
}

/**
 * Build the alt-text for an exercise media tile: "Demonstratie {nameRo}".
 * RO no-diacritics enforced via toExerciseDisplay.
 */
export function getExerciseMediaAlt(engineName: string): string {
  const display = toExerciseDisplay(engineName);
  return `Demonstratie ${display.name}`;
}
